/*
    This file is part of the WebKit open source project.
    This file has been generated by generate-bindings.pl. DO NOT MODIFY!

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public License
    along with this library; see the file COPYING.LIB.  If not, write to
    the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
    Boston, MA 02110-1301, USA.
*/

#include "config.h"
#include "JSCSSUnknownRule.h"

#include "CSSUnknownRule.h"
#include <wtf/GetPtr.h>

using namespace JSC;

namespace WebCore {

/* Hash table for prototype */

static const HashTableValue JSCSSUnknownRulePrototypeTableValues[] =
{
    { 0, 0, 0, 0, NoIntrinsic }
};

static const HashTable JSCSSUnknownRulePrototypeTable = { 1, 0, JSCSSUnknownRulePrototypeTableValues, 0 };
const ClassInfo JSCSSUnknownRulePrototype::s_info = { "CSSUnknownRulePrototype", &Base::s_info, &JSCSSUnknownRulePrototypeTable, 0, CREATE_METHOD_TABLE(JSCSSUnknownRulePrototype) };

JSObject* JSCSSUnknownRulePrototype::self(ExecState* exec, JSGlobalObject* globalObject)
{
    return getDOMPrototype<JSCSSUnknownRule>(exec, globalObject);
}

const ClassInfo JSCSSUnknownRule::s_info = { "CSSUnknownRule", &Base::s_info, 0, 0 , CREATE_METHOD_TABLE(JSCSSUnknownRule) };

JSCSSUnknownRule::JSCSSUnknownRule(Structure* structure, JSDOMGlobalObject* globalObject, PassRefPtr<CSSUnknownRule> impl)
    : JSCSSRule(structure, globalObject, impl)
{
}

void JSCSSUnknownRule::finishCreation(VM& vm)
{
    Base::finishCreation(vm);
    ASSERT(inherits(&s_info));
}

JSObject* JSCSSUnknownRule::createPrototype(ExecState* exec, JSGlobalObject* globalObject)
{
    return JSCSSUnknownRulePrototype::create(exec->vm(), globalObject, JSCSSUnknownRulePrototype::createStructure(exec->vm(), globalObject, JSCSSRulePrototype::self(exec, globalObject)));
}


}
